sudo: true
dist: trusty
language: python
python:
    - "3.5"
notifications:
    email: false

branches:
    only:
        - master

addons:
    firefox: "53.0"

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz 
    - gunzip geckodriver-v0.16.1-linux64.tar.gz && tar -xvf geckodriver-v0.16.1-linux64.tar

install:
    - pip install -r requirements.txt
    - pip install codecov

before_script:
    - export DISPLAY=:99.0
    - export PATH=$PATH:$(pwd)
    - sudo mv geckodriver /usr/local/bin
    - sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\"
    - sleep 3 # give xvfb some time to start
    - cd MechTurkLandmarker
    - make build

script:
    - make test

after_success:
    - codecov
